[package]
name = "lyripop"
version = "0.1.3"
description = "Floating Spotify mini-player with synced lyrics"
authors = ["m6bernha <matthias.bernhard7@gmail.com>"]
license = "MIT"
repository = "https://github.com/m6bernha/lyripop"
edition = "2021"

[lib]
name = "lyripop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
tauri-plugin-window-state = "2"
tauri-plugin-oauth = "2"
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
